[package]
name = "jute-rust-codegen"
version = "0.1.0"
authors = ["Jan Berktold <jan@berktold.co>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jute-rust-parser = { path = "../jute-rust-parser" }
codegen = "0.1.1"
