[package]
name = "jute-rust-codegen-test"
version = "0.1.0"
authors = ["Jan Berktold <jan@berktold.co>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
jute-rust-codegen = { path = "../jute-rust-codegen" }